version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-alpha.7
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "-----BEGIN CERTIFICATE-----\nMIIDETCCAfmgAwIBAgIJEN45PPUuEolLMA0GCSqGSIb3DQEBCwUAMCYxJDAiBgNV\nBAMTG2R5ZXJzaXR1YXRpb25zLnVzLmF1dGgwLmNvbTAeFw0yMDExMTUyMTAyNDFa\nFw0zNDA3MjUyMTAyNDFaMCYxJDAiBgNVBAMTG2R5ZXJzaXR1YXRpb25zLnVzLmF1\ndGgwLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJ76sS16DRoa\nHnMyh8PGy+08El8WiLCPBc1bw+805u7J9F98+TmvAVIVpGpGnELTlToTCk069SE5\n2OFPIIGEMtOMWFFgPu41cBfnm7Ww5Q9Af8VhVnjtpvO65Gf00VEZKl9Hq335uT9s\nXTMNDkVoUwTdnjk5wQF23SZQVOGjhQ+h+R9X3YXZ08FMptgVoS6UtTvXwyl1Q3yk\ns/RyTvJAibPdG5Pb0kN6dANYfVGv3l8eFGCjc/Zlqwswy9zK4f+tfKShR4MDqd0O\nkBeu7ACi2d8QMm61KFkTY40UDAPPWmcJmIVIvsQWShVqxcZ7dMo2KuVT8aQMxVvS\n3Y2rpE6qvs8CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUhTji\niG90TUXT/j00jnX7lgMl2m4wDgYDVR0PAQH/BAQDAgKEMA0GCSqGSIb3DQEBCwUA\nA4IBAQBlXpl8t22AWk72zXPipt1JI0BBcGWghQcdOJwisFmkkh7B6tQAcW0tbPqP\nJ9GTZaEHIPFnvyEKE/USv33ucvuFvjqVb2+MOcaBPEHUlytJqFG2dO0u2pAaRky3\n4+6SFOgeqhZGNFeYrO7wIO6EnMI9oqfnb6psAFTzcgSslR7F+d9L20k7fCzZiI+W\nXqwFMt5W46kZG+JLiOzFxE2IxKMohVGbSwhtreapJAelzUluHCTtUM/CYsNi2rWY\nQXwPjK6sT08zOBm5su/9EP8jZnMnCw0fixrovFTs9sjob9OQva0KUpkDbARi3kRG\nJLWrjtCDkDbadnQx2eEanHvcZseI\n-----END CERTIFICATE-----"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
volumes:
  db_data:
