version: "3.4"
services:
  ingress:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  caseydyer-nginx:
    image: dyersituations/catnginx:caseydyer
    depends_on:
      - caseydyer-app
    ports:
      - 81:80
    restart: always
    environment:
      - VIRTUAL_HOST=caseydyer.com
    volumes:
      - caseydyer-public:/var/www/public
  caseydyer-app:
    image: dyersituations/catcms:latest
    volumes:
      - caseydyer-db:/var/www/db
      - caseydyer-public:/var/www/public
    restart: always
volumes:
  caseydyer-db:
  caseydyer-public: