version: "3"
services:
  annfleming-nginx:
    build:
      context: ../
      dockerfile: nginx.Dockerfile
      args:
        APP_NAME: annfleming
  annfleming-app:
    build:
      context: ../catcms
      dockerfile: ../app.Dockerfile
      args:
        RAILS_ENV: "${RAILS_ENV}"
        SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
    volumes:
      - ../catcms:/var/www