on:
  workflow_dispatch:
    inputs:
      domain:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out catdocker repo
        uses: actions/checkout@v4
      - name: Check out catcms repo
        uses: actions/checkout@v4
        with:
          repository: dyersituations/catcms
          path: catcms
      - name: Create .env file
        run: |
          touch $GITHUB_WORKSPACE/.env
          echo RAILS_ENV=production >> .env
          echo SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }} >> .env
          cat $GITHUB_WORKSPACE/.env
      - name: Build images
        run: docker-compose -f "$GITHUB_WORKSPACE/${{ inputs.domain }}/docker-compose.yml" -f "$GITHUB_WORKSPACE/${{ inputs.domain }}/docker-compose.override.yml" build --no-cache
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push images
        run: docker-compose -f "$GITHUB_WORKSPACE/${{ inputs.domain }}/docker-compose.yml" -f "$GITHUB_WORKSPACE/${{ inputs.domain }}/docker-compose.override.yml" push
