on:
  workflow_dispatch:
    inputs:
      domain:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out catdocker repo
        uses: actions/checkout@v4
      - name: Check out catcms repo
        uses: actions/checkout@v4
        with:
          repository: dyersituations/catcms
          path: catcms
      - name: Create .env file
        run: |
          touch $GITHUB_WORKSPACE/${{ inputs.domain }}/.env
          echo RAILS_ENV=production >> .env
          echo SECRET_KEY_BASE=$(openssl rand -hex 64) >> .env
          cat $GITHUB_WORKSPACE/${{ inputs.domain }}/.env
      - name: Build images
        run: docker-compose build -f "$GITHUB_WORKSPACE/${{ inputs.domain }}/docker-compose.yml" --no-cache
