on:
  workflow_dispatch:
    inputs:
      domain:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out catdocker repo
        uses: actions/checkout@v4
      - name: Check out catcms repo
        uses: actions/checkout@v4
        with:
          repository: dyersituations/catcms
          path: catcms
      - name: Create .env file
        run: |
          touch ${{ github.workspace }}/.env
          echo RAILS_ENV=production >> .env
          echo SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }} >> .env
          cat ${{ github.workspace }}/.env
      - name: Build images
        run: |
          docker-compose \
            --env-file ${{ github.workspace }}/.env \
            -f ${{ github.workspace }}/${{ inputs.domain }}/docker-compose.yml \
            -f ${{ github.workspace }}/${{ inputs.domain }}/docker-compose.override.yml \
            build --no-cache
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push images
        run: |
          docker-compose \
            --env-file ${{ github.workspace }}/.env \
            -f "${{ github.workspace }}/${{ inputs.domain }}/docker-compose.yml" \
            -f "${{ github.workspace }}/${{ inputs.domain }}/docker-compose.override.yml" \
            push
      - name: Create host folder
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_KEY }}
          script: mkdir -p ${{ inputs.domain }}
      - name: Copy Docker files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_KEY }}
          source: "${{ github.workspace }}/${{ inputs.domain }}/docker-compose.yml"
          target: ${{ inputs.domain }}
      - name: Deploy updated images
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          key: ${{ secrets.DIGITAL_OCEAN_KEY }}
          script: |
            cd ${{ inputs.domain }}
            docker-compose pull && docker-compose up -d
